# Generated by Django 3.2.25 on 2026-09-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260913_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='haz_sizes',
            new_name='has_sizes',
        ),
    ]
